### ISSUE TITLE
建议不要弄根目录,指定一个目录名比较好

### ISSUE THREAD

**Issue by chainofhonor** [hanximeng/CloudDisk#2]
$dir = empty($_REQUEST["dir"]) ? 'file' : $_REQUEST["dir"];

中间加了一段 
指定访问file目录就行了  可以直接作为简易的网盘使用了 
配合WEBDEV 完全可以作为网盘用了

**Comment by chainofhonor** [comment]
另外请问那个css文件怎么下载下来? 

我访问css的地址发现里面的url 是代码 不是符号 比如http:// 就成了http%3A%2F%2F

**Comment by hanximeng** [comment]
- 关于地址变化的问题可以百度查询URL解码获取帮助。
- 指定文件目录已纳入考虑范围，预计将于下版本加入。
